#!/bin/bash

IN="eDP1"
EXT="DVI-I-1"

xrandr --listproviders | grep modesetting && xrandr --setprovideroutputsource 1 0

if (xrandr | grep "$EXT disconnected"); then
    xrandr --output $IN --auto --primary --output $EXT --off;
else
    xrandr --output $IN --auto --primary --output $EXT --mode 1280x720 --right-of $IN --brightness 1;
fi

