#!/bin/bash

IN="eDP1"
EXT="DP2"

if (xrandr | grep "$EXT disconnected"); then
    xrandr --output $IN --auto --primary --output $EXT --off;
else
    xrandr --output $IN --auto --primary --output $EXT --auto --right-of $IN --brightness 1;
fi

