#!/bin/bash
touchpadID=$(xinput list | grep "Synaptics" | awk -F "id=" '{print $2}'| grep -E '^[0-9]+' -o)
echo $touchpadID
touchpadEnabled=$(xinput list-props $touchpadID| grep "Device Enabled" | awk -F ":" '{print $2}')
if [ $touchpadEnabled -eq 1 ]
then
        xinput --set-prop $touchpadID "Device Enabled" 0 & notify-send "Touchpad Disabled"
else
        xinput --set-prop $touchpadID "Device Enabled" 1 & notify-send "Touchpad Enabled"
fi
